name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.6.1-bin.zip
        sudo mkdir /opt/gradle
        sudo unzip -d /opt/gradle gradle-7.6.1-bin.zip
        echo "export PATH=\$PATH:/opt/gradle/gradle-7.6.1/bin" >> $GITHUB_ENV
        
    - name: Clean Gradle Cache
      run: |
        rm -rf ~/.gradle/caches/
        rm -rf .gradle
        rm -rf build
        rm -rf app/build
        
    - name: Build APK
      run: |
        gradle --version
        gradle clean
        gradle assembleDebug --stacktrace
      
    - name: Create APK directory
      run: mkdir -p apk
      
    - name: Copy APK
      run: cp app/build/outputs/apk/debug/app-debug.apk apk/
      
    - name: Upload APK
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@apk/app-debug.apk" \
          "https://api.github.com/repos/${{ github.repository }}/contents/apk/app-debug.apk" 