name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Generate Gradle Wrapper
      run: |
        rm -rf gradle
        mkdir -p gradle/wrapper
        echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
        echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
        echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
        echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        wget -O gradle/wrapper/gradle-wrapper.jar https://services.gradle.org/distributions/gradle-7.6.1-bin.zip
        unzip -j gradle/wrapper/gradle-wrapper.jar gradle-7.6.1/lib/gradle-wrapper-7.6.1.jar -d gradle/wrapper/
        mv gradle/wrapper/gradle-wrapper-7.6.1.jar gradle/wrapper/gradle-wrapper.jar
        echo "#!/usr/bin/env sh" > gradlew
        echo "DIRNAME=\"\$(dirname \"\$(readlink -f \"\$0\")\")\"" >> gradlew
        echo "exec java -jar \"\$DIRNAME/gradle/wrapper/gradle-wrapper.jar\" \"\$@\"" >> gradlew
        chmod +x gradlew
        
    - name: Build APK
      run: ./gradlew assembleDebug
      
    - name: Create APK directory
      run: mkdir -p apk
      
    - name: Copy APK
      run: cp app/build/outputs/apk/debug/app-debug.apk apk/
      
    - name: Upload APK
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@apk/app-debug.apk" \
          "https://api.github.com/repos/${{ github.repository }}/contents/apk/app-debug.apk" 