name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK
      run: ./gradlew assembleDebug
      
    - name: Create APK directory
      run: mkdir -p apk
      
    - name: Copy APK
      run: cp app/build/outputs/apk/debug/app-debug.apk apk/
      
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app-debug
        path: apk/app-debug.apk 